# Generated by Django 5.1.4 on 2024-12-06 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0002_alter_favourite_unique_together'),
        ('posts', '0003_alter_post_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('owner', 'post')},
        ),
    ]
