# Generated by Django 3.2.4 on 2024-12-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at']},
        ),
    ]
